### ISSUE TITLE
No executable file(.exe) in this repo

### ISSUE THREAD

**Issue by Qinyihao** [23786/Cppp-IDE-Windows#1]
In Windows interference, you need to build an .exe in order to make it executable and being able to use.
So, you need to 

- [ ] Make a exe file.

**Comment by 23786** [comment]
There is a executable file in this repo.
In some path like bin/debug.
PS. This windows version of c+++ rarely updates and this application isn't well developed and so the application may look very strange on your PC.

**Comment by Qinyihao** [comment]
UI is strange enough...

**Comment by 23786** [comment]
1. spelling mistake: There is **an** executable file in this repo.
2. It looks very good on my mac(parallels desktop windows 10). Because I use the 2880*1800(or 2560*1600, I'm not very clear) retina screen which has a high resolution, the Visual Studio is also in the high resolution mode, so the executable file it compiled works well on my retina screen and is very very very very strange on screens which has a lower resolution.

**Comment by 23786** [comment]
But maybe it will look fine if I compile it in low resolution ....

**Comment by Qinyihao** [comment]
You can edit your comment.
